baseurl:

description: "This website chronicles my folly and ramblings, currently centred in <strong>London</strong>, where I'm living and working."

plugins:
  - jekyll-feed

permalink: pretty

tagline: "Type Applications"

title: "Tom Harding"

url: "http://www.tomharding.me"

disqus: www-tomharding-me
